import type { OpeningTag } from "./types";

// ECO code lookup: keyed by 3-char prefix (e.g. "A00"), with fallbacks by 2-char (e.g. "A0")
// Priority: exact 3-char match > 2-char range > 1-char volume letter

const ecoTags: Record<string, OpeningTag> = {
  // ─── A: Flank openings, English, Dutch, etc. ───────────────────────────────
  A00: {
    color: "white",
    style: "modern",
    character: "dynamic",
    complexity: "beginner",
    family: "Irregular Openings",
    ideas: [
      "Avoid conventional pawn centres to steer play into uncharted territory.",
      "Relies on opponent unfamiliarity rather than objective best play.",
      "White seeks flexibility, often transposing to known structures later.",
    ],
  },
  A01: {
    color: "white",
    style: "modern",
    character: "positional",
    complexity: "intermediate",
    family: "Nimzo-Larsen Attack",
    ideas: [
      "1.b3 develops the bishop to b2, controlling the long diagonal.",
      "Avoids standard pawn-centre battles in favour of piece activity.",
      "Popular at club level; Fischer and Larsen championed it at the highest level.",
    ],
  },
  A02: {
    color: "white",
    style: "modern",
    character: "dynamic",
    complexity: "beginner",
    family: "Bird's Opening",
    ideas: [
      "1.f4 controls e5 and prepares a kingside build-up.",
      "Can transpose to the From's Gambit if Black plays 1...e5.",
      "White aims for a 'reversed Dutch' setup with aggressive kingside chances.",
    ],
  },
  A03: {
    color: "white",
    style: "modern",
    character: "dynamic",
    complexity: "beginner",
    family: "Bird's Opening",
    ideas: [
      "After 1.f4 d5, White bolsters the f4 thrust with Nf3 and g3.",
      "Queenside play remains an option while kingside pressure builds.",
    ],
  },
  A04: {
    color: "white",
    style: "modern",
    character: "positional",
    complexity: "intermediate",
    family: "Réti Opening",
    ideas: [
      "1.Nf3 delays commitment, keeping maximum flexibility.",
      "Can transpose to Queen's Gambit, King's Indian Attack, or English.",
      "White controls d4 and e5 with pieces before advancing pawns.",
    ],
  },
  A05: {
    color: "white",
    style: "modern",
    character: "positional",
    complexity: "intermediate",
    family: "Réti Opening",
    ideas: [
      "1.Nf3 Nf6 — both sides develop knights symmetrically.",
      "White often follows with g3 and Bg2 for a hypermodern setup.",
      "Flexible: can become King's Indian Attack, English, or Catalan.",
    ],
  },
  A06: {
    color: "white",
    style: "hypermodern",
    character: "positional",
    complexity: "intermediate",
    family: "Réti Opening",
    ideas: [
      "1.Nf3 d5 2.b3 — White fianchettoes the queenside bishop.",
      "Indirect pressure on d5 through the b2 bishop.",
      "Avoids the symmetrical positions of the pure English.",
    ],
  },
  A07: {
    color: "white",
    style: "modern",
    character: "positional",
    complexity: "intermediate",
    family: "King's Indian Attack",
    ideas: [
      "Nf3 + g3 + Bg2 setup mirrors the King's Indian Defence structure.",
      "White builds a solid pawn triangle and attacks on the kingside.",
      "Effective against the French, Caro-Kann, and Sicilian as White.",
    ],
  },
  A08: {
    color: "white",
    style: "modern",
    character: "positional",
    complexity: "intermediate",
    family: "King's Indian Attack",
    ideas: [
      "After 1.Nf3 d5 2.g3, White prepares e4 with a fianchettoed bishop.",
      "Long-term kingside initiative with a very solid foundation.",
    ],
  },
  A09: {
    color: "white",
    style: "hypermodern",
    character: "positional",
    complexity: "intermediate",
    family: "Réti Opening",
    ideas: [
      "1.Nf3 d5 2.c4 — the main Réti, immediately challenging d5.",
      "White avoids an early centre and instead undermines it with c4.",
      "Can transpose to Queen's Gambit lines or remain independent.",
    ],
  },

  // A10–A39: English Opening
  A10: {
    color: "white",
    style: "modern",
    character: "positional",
    complexity: "intermediate",
    family: "English Opening",
    ideas: [
      "1.c4 stakes a claim on d5 without occupying the centre with pawns.",
      "Extremely flexible — can transpose to many structures.",
      "Favoured by positional players who want to control the game's direction.",
    ],
  },
  A11: {
    color: "white",
    style: "modern",
    character: "positional",
    complexity: "intermediate",
    family: "English Opening",
    ideas: [
      "English with ...c6 — Black's Caro-Kann setup against 1.c4.",
      "Solid and compact; Black aims for d5 at an opportune moment.",
    ],
  },
  A12: {
    color: "white",
    style: "modern",
    character: "positional",
    complexity: "intermediate",
    family: "English Opening",
  },
  A13: {
    color: "white",
    style: "modern",
    character: "positional",
    complexity: "intermediate",
    family: "English Opening",
    ideas: [
      "English Opening with ...e6 — Black supports a future d5.",
      "Often leads to Queen's Gambit-style positions with colours reversed.",
      "White uses the half-open d-file for queenside pressure.",
    ],
  },
  A14: {
    color: "white",
    style: "modern",
    character: "positional",
    complexity: "intermediate",
    family: "English Opening",
  },
  A15: {
    color: "white",
    style: "hypermodern",
    character: "positional",
    complexity: "intermediate",
    family: "English Opening",
  },
  A16: {
    color: "white",
    style: "modern",
    character: "positional",
    complexity: "intermediate",
    family: "English Opening",
  },
  A17: {
    color: "white",
    style: "modern",
    character: "positional",
    complexity: "intermediate",
    family: "English Opening",
    ideas: [
      "English vs Nimzo — Black develops the bishop to b4 early.",
      "Rich positional play with tension over the d4 and e5 squares.",
    ],
  },
  A18: {
    color: "white",
    style: "modern",
    character: "positional",
    complexity: "intermediate",
    family: "English Opening",
  },
  A19: {
    color: "white",
    style: "modern",
    character: "dynamic",
    complexity: "intermediate",
    family: "English Opening",
  },
  A20: {
    color: "white",
    style: "modern",
    character: "positional",
    complexity: "intermediate",
    family: "English Opening",
    ideas: [
      "1.c4 e5 — English Opening, Reversed Sicilian structure.",
      "White has an extra tempo compared to the Sicilian as Black.",
      "Manoeuvring and piece play dominate; pawn breaks often come late.",
    ],
  },
  A21: {
    color: "white",
    style: "modern",
    character: "dynamic",
    complexity: "intermediate",
    family: "English Opening",
  },
  A22: {
    color: "white",
    style: "modern",
    character: "dynamic",
    complexity: "intermediate",
    family: "English Opening",
  },
  A25: {
    color: "white",
    style: "modern",
    character: "dynamic",
    complexity: "intermediate",
    family: "English Opening",
  },
  A28: {
    color: "white",
    style: "modern",
    character: "positional",
    complexity: "intermediate",
    family: "English Opening",
  },
  A30: {
    color: "white",
    style: "modern",
    character: "positional",
    complexity: "intermediate",
    family: "English Opening",
    ideas: [
      "Symmetrical English: both sides mirror with c4/c5.",
      "Highly strategic; tiny imbalances decide the game.",
      "A favourite of world-class players seeking long technical battles.",
    ],
  },
  A34: {
    color: "white",
    style: "modern",
    character: "positional",
    complexity: "intermediate",
    family: "English Opening",
  },
  A36: {
    color: "white",
    style: "modern",
    character: "positional",
    complexity: "advanced",
    family: "English Opening",
  },
  A37: {
    color: "white",
    style: "modern",
    character: "positional",
    complexity: "advanced",
    family: "English Opening",
  },
  A38: {
    color: "white",
    style: "modern",
    character: "positional",
    complexity: "advanced",
    family: "English Opening",
  },
  A39: {
    color: "white",
    style: "modern",
    character: "dynamic",
    complexity: "advanced",
    family: "English Opening",
  },

  // A40–A49: Queen's Pawn miscellaneous
  A40: {
    color: "white",
    style: "classical",
    character: "solid",
    complexity: "beginner",
    family: "Queen's Pawn",
    ideas: [
      "1.d4 — controls the centre immediately and opens lines for development.",
      "A wide family of openings; Black has many ways to respond.",
    ],
  },
  A41: {
    color: "black",
    style: "modern",
    character: "solid",
    complexity: "intermediate",
    family: "Queen's Pawn",
  },
  A42: {
    color: "black",
    style: "modern",
    character: "solid",
    complexity: "intermediate",
    family: "Modern Defence",
    ideas: [
      "Modern Defence / Averbakh — Black delays d5 and fianchettoes.",
      "Flexible setup that avoids early commitment.",
      "White must play accurately to exploit the tempo gained.",
    ],
  },
  A43: {
    color: "black",
    style: "modern",
    character: "solid",
    complexity: "intermediate",
    family: "Benoni",
  },
  A44: {
    color: "black",
    style: "modern",
    character: "dynamic",
    complexity: "intermediate",
    family: "Benoni",
  },
  A45: {
    color: "white",
    style: "classical",
    character: "solid",
    complexity: "beginner",
    family: "Queen's Pawn",
    ideas: [
      "1.d4 Nf6 — most common response to d4.",
      "Sets up Indian-style defences or can lead to d5 systems.",
    ],
  },
  A46: {
    color: "white",
    style: "classical",
    character: "positional",
    complexity: "intermediate",
    family: "Queen's Pawn",
  },
  A47: {
    color: "white",
    style: "modern",
    character: "positional",
    complexity: "intermediate",
    family: "Queen's Indian",
  },
  A48: {
    color: "white",
    style: "modern",
    character: "positional",
    complexity: "intermediate",
    family: "King's Indian",
  },
  A49: {
    color: "white",
    style: "modern",
    character: "positional",
    complexity: "intermediate",
    family: "King's Indian",
  },

  // A50–A79: Queen's Pawn and Indian systems
  A50: {
    color: "black",
    style: "modern",
    character: "dynamic",
    complexity: "intermediate",
    family: "Indian Defences",
  },
  A51: {
    color: "black",
    style: "modern",
    character: "dynamic",
    complexity: "intermediate",
    family: "Budapest Gambit",
    ideas: [
      "1.d4 Nf6 2.c4 e5 — Budapest Gambit sacrifices a pawn for activity.",
      "Black gets rapid piece development in exchange for the e5 pawn.",
      "Dangerous at club level; objectively White should be slightly better.",
    ],
  },
  A52: {
    color: "black",
    style: "modern",
    character: "tactical",
    complexity: "intermediate",
    family: "Budapest Gambit",
    ideas: [
      "Budapest Gambit accepted: Black's pieces flood the board.",
      "Active counterplay compensates for the structural weaknesses.",
    ],
  },
  A53: {
    color: "black",
    style: "modern",
    character: "solid",
    complexity: "intermediate",
    family: "Old Indian Defence",
  },
  A54: {
    color: "black",
    style: "modern",
    character: "solid",
    complexity: "intermediate",
    family: "Old Indian Defence",
  },
  A55: {
    color: "black",
    style: "modern",
    character: "solid",
    complexity: "intermediate",
    family: "Old Indian Defence",
  },
  A56: {
    color: "black",
    style: "modern",
    character: "dynamic",
    complexity: "intermediate",
    family: "Benoni",
  },
  A57: {
    color: "black",
    style: "modern",
    character: "aggressive",
    complexity: "advanced",
    family: "Benko Gambit",
    ideas: [
      "Benko Gambit: Black sacrifices the b5 pawn for long-term queenside pressure.",
      "Compensation comes in the form of the open a- and b-files.",
      "White is technically better but Black has easy, active play.",
    ],
  },
  A58: {
    color: "black",
    style: "modern",
    character: "aggressive",
    complexity: "advanced",
    family: "Benko Gambit",
  },
  A59: {
    color: "black",
    style: "modern",
    character: "aggressive",
    complexity: "advanced",
    family: "Benko Gambit",
  },
  A60: {
    color: "black",
    style: "modern",
    character: "dynamic",
    complexity: "intermediate",
    family: "Benoni",
    ideas: [
      "Modern Benoni: ...c5 challenges White's centre after d4.",
      "Asymmetrical pawn structure leads to rich, double-edged play.",
      "Black accepts a long-term weakness on d6 for dynamic counterplay.",
    ],
  },
  A61: {
    color: "black",
    style: "modern",
    character: "dynamic",
    complexity: "advanced",
    family: "Benoni",
  },
  A62: {
    color: "black",
    style: "modern",
    character: "dynamic",
    complexity: "advanced",
    family: "Benoni",
  },
  A63: {
    color: "black",
    style: "modern",
    character: "dynamic",
    complexity: "advanced",
    family: "Benoni",
  },
  A64: {
    color: "black",
    style: "modern",
    character: "dynamic",
    complexity: "advanced",
    family: "Benoni",
  },
  A65: {
    color: "black",
    style: "modern",
    character: "aggressive",
    complexity: "advanced",
    family: "Benoni",
  },
  A66: {
    color: "black",
    style: "modern",
    character: "aggressive",
    complexity: "advanced",
    family: "Benoni",
  },
  A67: {
    color: "black",
    style: "modern",
    character: "aggressive",
    complexity: "advanced",
    family: "Benoni",
  },
  A68: {
    color: "black",
    style: "modern",
    character: "aggressive",
    complexity: "advanced",
    family: "Benoni",
  },
  A69: {
    color: "black",
    style: "modern",
    character: "aggressive",
    complexity: "advanced",
    family: "Benoni",
  },
  A70: {
    color: "black",
    style: "modern",
    character: "aggressive",
    complexity: "advanced",
    family: "Benoni",
  },
  A71: {
    color: "black",
    style: "modern",
    character: "aggressive",
    complexity: "advanced",
    family: "Benoni",
  },
  A72: {
    color: "black",
    style: "modern",
    character: "aggressive",
    complexity: "advanced",
    family: "Benoni",
  },
  A73: {
    color: "black",
    style: "modern",
    character: "dynamic",
    complexity: "advanced",
    family: "Benoni",
  },
  A74: {
    color: "black",
    style: "modern",
    character: "dynamic",
    complexity: "advanced",
    family: "Benoni",
  },
  A75: {
    color: "black",
    style: "modern",
    character: "dynamic",
    complexity: "advanced",
    family: "Benoni",
  },
  A76: {
    color: "black",
    style: "modern",
    character: "dynamic",
    complexity: "advanced",
    family: "Benoni",
  },
  A77: {
    color: "black",
    style: "modern",
    character: "dynamic",
    complexity: "advanced",
    family: "Benoni",
  },
  A78: {
    color: "black",
    style: "modern",
    character: "dynamic",
    complexity: "advanced",
    family: "Benoni",
  },
  A79: {
    color: "black",
    style: "modern",
    character: "dynamic",
    complexity: "advanced",
    family: "Benoni",
  },

  // A80–A99: Dutch Defence
  A80: {
    color: "black",
    style: "modern",
    character: "aggressive",
    complexity: "intermediate",
    family: "Dutch Defence",
    ideas: [
      "Dutch Defence: 1...f5 seizes kingside space immediately.",
      "Black gets attacking chances on the kingside at the cost of a structural weakness on e6.",
      "Favoured by attacking players who enjoy unbalanced positions.",
    ],
  },
  A81: {
    color: "black",
    style: "modern",
    character: "aggressive",
    complexity: "intermediate",
    family: "Dutch Defence",
  },
  A82: {
    color: "black",
    style: "modern",
    character: "tactical",
    complexity: "intermediate",
    family: "Dutch Defence",
  },
  A83: {
    color: "black",
    style: "modern",
    character: "tactical",
    complexity: "intermediate",
    family: "Dutch Defence",
  },
  A84: {
    color: "black",
    style: "modern",
    character: "aggressive",
    complexity: "intermediate",
    family: "Dutch Defence",
  },
  A85: {
    color: "black",
    style: "modern",
    character: "aggressive",
    complexity: "intermediate",
    family: "Dutch Defence",
  },
  A86: {
    color: "black",
    style: "modern",
    character: "aggressive",
    complexity: "intermediate",
    family: "Dutch Defence",
  },
  A87: {
    color: "black",
    style: "modern",
    character: "dynamic",
    complexity: "intermediate",
    family: "Dutch Defence",
    ideas: [
      "Leningrad Dutch: Black fianchettoes the bishop to g7.",
      "Combines the Dutch f5 with a King's Indian-style build.",
      "Piece activity and the g7 bishop provide long-term compensation.",
    ],
  },
  A88: {
    color: "black",
    style: "modern",
    character: "dynamic",
    complexity: "intermediate",
    family: "Dutch Defence",
  },
  A89: {
    color: "black",
    style: "modern",
    character: "dynamic",
    complexity: "advanced",
    family: "Dutch Defence",
  },
  A90: {
    color: "black",
    style: "classical",
    character: "solid",
    complexity: "intermediate",
    family: "Dutch Defence",
  },
  A91: {
    color: "black",
    style: "classical",
    character: "solid",
    complexity: "intermediate",
    family: "Dutch Defence",
  },
  A92: {
    color: "black",
    style: "classical",
    character: "solid",
    complexity: "intermediate",
    family: "Dutch Defence",
  },
  A93: {
    color: "black",
    style: "classical",
    character: "solid",
    complexity: "intermediate",
    family: "Dutch Defence",
  },
  A94: {
    color: "black",
    style: "classical",
    character: "solid",
    complexity: "intermediate",
    family: "Dutch Defence",
  },
  A95: {
    color: "black",
    style: "classical",
    character: "solid",
    complexity: "intermediate",
    family: "Dutch Defence",
  },
  A96: {
    color: "black",
    style: "classical",
    character: "solid",
    complexity: "intermediate",
    family: "Dutch Defence",
  },
  A97: {
    color: "black",
    style: "classical",
    character: "solid",
    complexity: "advanced",
    family: "Dutch Defence",
    ideas: [
      "Classical Dutch / Ilyin-Zhenevsky: ...Be7, ...d6, ...Qe8 build.",
      "Black aims to advance ...e5 when conditions are right.",
      "Very classical and manoeuvring — a true test of strategic understanding.",
    ],
  },
  A98: {
    color: "black",
    style: "classical",
    character: "solid",
    complexity: "advanced",
    family: "Dutch Defence",
  },
  A99: {
    color: "black",
    style: "classical",
    character: "positional",
    complexity: "advanced",
    family: "Dutch Defence",
  },

  // ─── B: Semi-open games ─────────────────────────────────────────────────────
  B00: {
    color: "black",
    style: "modern",
    character: "dynamic",
    complexity: "beginner",
    family: "Semi-Open Games",
    ideas: [
      "Unusual defences to 1.e4 — avoids main theory.",
      "Black seeks unorthodox positions to destabilise the game early.",
    ],
  },
  B01: {
    color: "black",
    style: "classical",
    character: "solid",
    complexity: "intermediate",
    family: "Scandinavian Defence",
    ideas: [
      "1...d5 immediately challenges White's e-pawn.",
      "After 2.exd5 Qxd5, Black's queen must move again but is active.",
      "Solid and direct; popular at club level for its clear strategic aims.",
    ],
  },
  B02: {
    color: "black",
    style: "modern",
    character: "aggressive",
    complexity: "intermediate",
    family: "Alekhine's Defence",
    ideas: [
      "1...Nf6 invites White to chase the knight and overextend.",
      "Black's strategy: provoke White's pawns, then attack them.",
      "Alekhine's Defence was a favourite of World Champion Alekhine.",
    ],
  },
  B03: {
    color: "black",
    style: "modern",
    character: "aggressive",
    complexity: "intermediate",
    family: "Alekhine's Defence",
  },
  B04: {
    color: "black",
    style: "modern",
    character: "dynamic",
    complexity: "advanced",
    family: "Alekhine's Defence",
    ideas: [
      "Modern Variation: Black maintains ...Nf6 pressure on e4.",
      "White's pawn centre becomes a target for Black's pieces.",
    ],
  },
  B05: {
    color: "black",
    style: "modern",
    character: "dynamic",
    complexity: "advanced",
    family: "Alekhine's Defence",
  },
  B06: {
    color: "black",
    style: "modern",
    character: "solid",
    complexity: "intermediate",
    family: "Modern Defence",
    ideas: [
      "Modern Defence / Robatsch: Black fianchettoes to g7.",
      "Delays centre confrontation until piece development is complete.",
      "Flexible — can transpose to many Indian structures.",
    ],
  },
  B07: {
    color: "black",
    style: "modern",
    character: "solid",
    complexity: "intermediate",
    family: "Pirc Defence",
    ideas: [
      "Pirc Defence: ...d6, ...Nf6, ...g6 — classical hypermodern setup.",
      "Black invites White to build a large centre then attacks it.",
      "Kasparov used the Pirc periodically at the highest level.",
    ],
  },
  B08: {
    color: "black",
    style: "modern",
    character: "solid",
    complexity: "intermediate",
    family: "Pirc Defence",
  },
  B09: {
    color: "black",
    style: "modern",
    character: "aggressive",
    complexity: "advanced",
    family: "Pirc Defence",
    ideas: [
      "Pirc Austrian Attack: White plays f4, aiming for a kingside storm.",
      "Sharp, tactical battles with mutual attacking chances.",
    ],
  },
  B10: {
    color: "black",
    style: "classical",
    character: "solid",
    complexity: "intermediate",
    family: "Caro-Kann Defence",
    ideas: [
      "Caro-Kann: 1...c6 prepares ...d5 with solid pawn structure.",
      "Black avoids the doubled pawns of the French.",
      "A favourite of positional players who want a solid foundation.",
    ],
  },
  B11: {
    color: "black",
    style: "classical",
    character: "solid",
    complexity: "intermediate",
    family: "Caro-Kann Defence",
  },
  B12: {
    color: "black",
    style: "classical",
    character: "solid",
    complexity: "intermediate",
    family: "Caro-Kann Defence",
    ideas: [
      "Advance Variation: 3.e5 — White claims space immediately.",
      "Black aims for ...c5 to attack the extended pawn chain.",
      "Long-term positional battle with fewer tactical fireworks.",
    ],
  },
  B13: {
    color: "black",
    style: "classical",
    character: "solid",
    complexity: "intermediate",
    family: "Caro-Kann Defence",
    ideas: [
      "Exchange Variation: 3.exd5 cxd5 — symmetrical pawn structure.",
      "White's slight development advantage is the only imbalance.",
    ],
  },
  B14: {
    color: "black",
    style: "classical",
    character: "solid",
    complexity: "intermediate",
    family: "Caro-Kann Defence",
  },
  B15: {
    color: "black",
    style: "classical",
    character: "solid",
    complexity: "intermediate",
    family: "Caro-Kann Defence",
  },
  B16: {
    color: "black",
    style: "classical",
    character: "solid",
    complexity: "intermediate",
    family: "Caro-Kann Defence",
    ideas: [
      "Bronstein-Larsen: 1.e4 c6 2.d4 d5 3.Nc3 dxe4 4.Nxe4 Nf6 5.Nxf6+ gxf6.",
      "Black accepts doubled pawns for the two bishops and an open g-file.",
    ],
  },
  B17: {
    color: "black",
    style: "classical",
    character: "solid",
    complexity: "intermediate",
    family: "Caro-Kann Defence",
    ideas: [
      "Steinitz Variation: Black retreats the bishop to d7 after 4.Nxe4 Nd7.",
      "Very solid but slightly passive — typical Caro-Kann resilience.",
    ],
  },
  B18: {
    color: "black",
    style: "classical",
    character: "solid",
    complexity: "intermediate",
    family: "Caro-Kann Defence",
    ideas: [
      "Classical Caro-Kann: 4...Bf5 — Black develops the bishop outside the pawn chain.",
      "One of the most theoretically important Caro-Kann lines.",
      "Petrosian, Karpov, and Anand all employed this variation.",
    ],
  },
  B19: {
    color: "black",
    style: "classical",
    character: "solid",
    complexity: "advanced",
    family: "Caro-Kann Defence",
    ideas: [
      "Classical Caro-Kann main line: very deeply theoretical.",
      "Black achieves a solid position with the bishop on f5.",
      "White must play precisely to extract an advantage.",
    ],
  },
  B20: {
    color: "black",
    style: "modern",
    character: "dynamic",
    complexity: "intermediate",
    family: "Sicilian Defence",
    ideas: [
      "Sicilian Defence: 1...c5 fights for d4 without symmetry.",
      "The most popular and theoretically extensive defence to 1.e4.",
      "Black concedes the centre temporarily to counterattack later.",
    ],
  },
  B21: {
    color: "black",
    style: "modern",
    character: "tactical",
    complexity: "intermediate",
    family: "Sicilian Defence",
    ideas: [
      "Grand Prix Attack / Smith-Morra Gambit — White attacks immediately.",
      "f4-f5 pawn advance creates direct kingside threats.",
    ],
  },
  B22: {
    color: "black",
    style: "modern",
    character: "dynamic",
    complexity: "intermediate",
    family: "Sicilian Defence",
    ideas: [
      "Alapin Variation: 2.c3 prepares a strong centre with d4.",
      "Popular anti-Sicilian — avoids heavy theory of the Open Sicilian.",
      "Black must be careful about White's quick development and central control.",
    ],
  },
  B23: {
    color: "black",
    style: "modern",
    character: "dynamic",
    complexity: "intermediate",
    family: "Sicilian Defence",
    ideas: [
      "Grand Prix Attack: 2.Nc3 + f4 aims for a quick kingside assault.",
      "Favourite of club players; Nigel Short popularised it at the top level.",
    ],
  },
  B24: {
    color: "black",
    style: "modern",
    character: "dynamic",
    complexity: "intermediate",
    family: "Sicilian Defence",
  },
  B25: {
    color: "black",
    style: "modern",
    character: "dynamic",
    complexity: "intermediate",
    family: "Sicilian Defence",
  },
  B27: {
    color: "black",
    style: "modern",
    character: "dynamic",
    complexity: "intermediate",
    family: "Sicilian Defence",
  },
  B28: {
    color: "black",
    style: "modern",
    character: "dynamic",
    complexity: "intermediate",
    family: "Sicilian Defence",
  },
  B29: {
    color: "black",
    style: "modern",
    character: "dynamic",
    complexity: "intermediate",
    family: "Sicilian Defence",
  },
  B30: {
    color: "black",
    style: "modern",
    character: "dynamic",
    complexity: "intermediate",
    family: "Sicilian Defence",
  },
  B31: {
    color: "black",
    style: "modern",
    character: "dynamic",
    complexity: "intermediate",
    family: "Sicilian Defence",
  },
  B32: {
    color: "black",
    style: "modern",
    character: "dynamic",
    complexity: "intermediate",
    family: "Sicilian Defence",
  },
  B33: {
    color: "black",
    style: "modern",
    character: "dynamic",
    complexity: "intermediate",
    family: "Sicilian Defence",
    ideas: [
      "Sveshnikov / Pelikan: ...e5 after Nf3+d4 secures d4 for Black.",
      "Black accepts a weak d5 square for massive counterplay on the queenside.",
      "Kasparov's use propelled this to one of the most analysed Sicilian systems.",
    ],
  },
  B40: {
    color: "black",
    style: "modern",
    character: "dynamic",
    complexity: "intermediate",
    family: "Sicilian Defence",
  },
  B41: {
    color: "black",
    style: "modern",
    character: "dynamic",
    complexity: "intermediate",
    family: "Sicilian Defence",
  },
  B42: {
    color: "black",
    style: "modern",
    character: "dynamic",
    complexity: "intermediate",
    family: "Sicilian Defence",
  },
  B43: {
    color: "black",
    style: "modern",
    character: "dynamic",
    complexity: "intermediate",
    family: "Sicilian Defence",
  },
  B44: {
    color: "black",
    style: "modern",
    character: "dynamic",
    complexity: "intermediate",
    family: "Sicilian Defence",
  },
  B45: {
    color: "black",
    style: "modern",
    character: "dynamic",
    complexity: "intermediate",
    family: "Sicilian Defence",
  },
  B46: {
    color: "black",
    style: "modern",
    character: "dynamic",
    complexity: "intermediate",
    family: "Sicilian Defence",
  },
  B47: {
    color: "black",
    style: "modern",
    character: "dynamic",
    complexity: "intermediate",
    family: "Sicilian Defence",
  },
  B48: {
    color: "black",
    style: "modern",
    character: "dynamic",
    complexity: "intermediate",
    family: "Sicilian Defence",
  },
  B49: {
    color: "black",
    style: "modern",
    character: "dynamic",
    complexity: "intermediate",
    family: "Sicilian Defence",
  },
  B50: {
    color: "black",
    style: "modern",
    character: "dynamic",
    complexity: "intermediate",
    family: "Sicilian Defence",
  },
  B51: {
    color: "black",
    style: "modern",
    character: "dynamic",
    complexity: "intermediate",
    family: "Sicilian Defence",
  },
  B52: {
    color: "black",
    style: "modern",
    character: "dynamic",
    complexity: "intermediate",
    family: "Sicilian Defence",
  },
  B53: {
    color: "black",
    style: "modern",
    character: "dynamic",
    complexity: "intermediate",
    family: "Sicilian Defence",
  },
  B54: {
    color: "black",
    style: "modern",
    character: "dynamic",
    complexity: "advanced",
    family: "Sicilian Defence",
  },
  B57: {
    color: "black",
    style: "modern",
    character: "dynamic",
    complexity: "advanced",
    family: "Sicilian Defence",
  },
  B60: {
    color: "black",
    style: "modern",
    character: "dynamic",
    complexity: "advanced",
    family: "Sicilian Defence",
  },
  B70: {
    color: "black",
    style: "modern",
    character: "dynamic",
    complexity: "intermediate",
    family: "Sicilian Dragon",
    ideas: [
      "Dragon Variation: ...g6 and ...Bg7 create a powerful fianchetto.",
      "One of the sharpest openings in chess — both sides attack.",
      "White typically castles queenside to rush a kingside attack.",
      "The g7 dragon bishop is Black's key attacking piece.",
    ],
  },
  B71: {
    color: "black",
    style: "modern",
    character: "dynamic",
    complexity: "intermediate",
    family: "Sicilian Dragon",
  },
  B72: {
    color: "black",
    style: "modern",
    character: "dynamic",
    complexity: "intermediate",
    family: "Sicilian Dragon",
  },
  B73: {
    color: "black",
    style: "modern",
    character: "dynamic",
    complexity: "intermediate",
    family: "Sicilian Dragon",
  },
  B74: {
    color: "black",
    style: "modern",
    character: "dynamic",
    complexity: "advanced",
    family: "Sicilian Dragon",
  },
  B75: {
    color: "black",
    style: "modern",
    character: "aggressive",
    complexity: "advanced",
    family: "Sicilian Dragon",
  },
  B76: {
    color: "black",
    style: "modern",
    character: "aggressive",
    complexity: "advanced",
    family: "Sicilian Dragon",
    ideas: [
      "Yugoslav Attack: White castles queenside and launches h4-h5.",
      "Race: White attacks on the kingside, Black on the queenside.",
      "One of the most deeply analysed systems in all of chess.",
    ],
  },
  B77: {
    color: "black",
    style: "modern",
    character: "aggressive",
    complexity: "advanced",
    family: "Sicilian Dragon",
  },
  B78: {
    color: "black",
    style: "modern",
    character: "aggressive",
    complexity: "advanced",
    family: "Sicilian Dragon",
  },
  B79: {
    color: "black",
    style: "modern",
    character: "aggressive",
    complexity: "advanced",
    family: "Sicilian Dragon",
  },
  B80: {
    color: "black",
    style: "modern",
    character: "dynamic",
    complexity: "advanced",
    family: "Sicilian Scheveningen",
    ideas: [
      "Scheveningen: ...e6 creates a small centre with ...d6.",
      "Black's position is solid but must withstand White's attacking tries.",
      "Karpov and Kasparov both played it at world championship level.",
    ],
  },
  B81: {
    color: "black",
    style: "modern",
    character: "dynamic",
    complexity: "advanced",
    family: "Sicilian Scheveningen",
  },
  B82: {
    color: "black",
    style: "modern",
    character: "aggressive",
    complexity: "advanced",
    family: "Sicilian Scheveningen",
  },
  B83: {
    color: "black",
    style: "modern",
    character: "dynamic",
    complexity: "advanced",
    family: "Sicilian Scheveningen",
  },
  B84: {
    color: "black",
    style: "modern",
    character: "dynamic",
    complexity: "advanced",
    family: "Sicilian Scheveningen",
  },
  B85: {
    color: "black",
    style: "modern",
    character: "positional",
    complexity: "advanced",
    family: "Sicilian Scheveningen",
  },
  B86: {
    color: "black",
    style: "modern",
    character: "dynamic",
    complexity: "advanced",
    family: "Sicilian Scheveningen",
  },
  B87: {
    color: "black",
    style: "modern",
    character: "aggressive",
    complexity: "advanced",
    family: "Sicilian Scheveningen",
  },
  B88: {
    color: "black",
    style: "modern",
    character: "positional",
    complexity: "advanced",
    family: "Sicilian Scheveningen",
  },
  B89: {
    color: "black",
    style: "modern",
    character: "aggressive",
    complexity: "advanced",
    family: "Sicilian Scheveningen",
  },
  B90: {
    color: "black",
    style: "modern",
    character: "aggressive",
    complexity: "advanced",
    family: "Sicilian Najdorf",
    ideas: [
      "Najdorf Variation: ...a6 secures b5 for pieces and prepares ...e5/...b5.",
      "The most played opening in modern grandmaster chess.",
      "Fischer and Kasparov were its greatest proponents.",
      "Black accepts a passive position temporarily for maximum counterplay.",
    ],
  },
  B91: {
    color: "black",
    style: "modern",
    character: "aggressive",
    complexity: "advanced",
    family: "Sicilian Najdorf",
  },
  B92: {
    color: "black",
    style: "modern",
    character: "dynamic",
    complexity: "advanced",
    family: "Sicilian Najdorf",
  },
  B93: {
    color: "black",
    style: "modern",
    character: "aggressive",
    complexity: "advanced",
    family: "Sicilian Najdorf",
  },
  B94: {
    color: "black",
    style: "modern",
    character: "aggressive",
    complexity: "advanced",
    family: "Sicilian Najdorf",
  },
  B95: {
    color: "black",
    style: "modern",
    character: "aggressive",
    complexity: "advanced",
    family: "Sicilian Najdorf",
  },
  B96: {
    color: "black",
    style: "modern",
    character: "aggressive",
    complexity: "advanced",
    family: "Sicilian Najdorf",
    ideas: [
      "Poisoned Pawn Variation: Black's queen grabs on b2.",
      "Extremely risky but heavily analysed — needs precise knowledge.",
    ],
  },
  B97: {
    color: "black",
    style: "modern",
    character: "aggressive",
    complexity: "advanced",
    family: "Sicilian Najdorf",
  },
  B98: {
    color: "black",
    style: "modern",
    character: "dynamic",
    complexity: "advanced",
    family: "Sicilian Najdorf",
  },
  B99: {
    color: "black",
    style: "modern",
    character: "dynamic",
    complexity: "advanced",
    family: "Sicilian Najdorf",
  },

  // ─── C: Open games, French, Spanish ─────────────────────────────────────────
  C00: {
    color: "black",
    style: "classical",
    character: "solid",
    complexity: "beginner",
    family: "French Defence",
    ideas: [
      "French Defence: 1...e6 prepares ...d5 with solid pawn chain.",
      "Black accepts a slightly cramped position for long-term solidity.",
      "The light-squared bishop on c8 can be a problem piece.",
    ],
  },
  C01: {
    color: "black",
    style: "classical",
    character: "solid",
    complexity: "intermediate",
    family: "French Defence",
    ideas: [
      "Exchange Variation: 3.exd5 — simplifies to a symmetrical structure.",
      "White retains a slight initiative but Black should equalise.",
    ],
  },
  C02: {
    color: "black",
    style: "classical",
    character: "solid",
    complexity: "intermediate",
    family: "French Defence",
    ideas: [
      "Advance Variation: 3.e5 — White gains space but creates targets.",
      "Black attacks the pawn chain with ...c5 and ...f6.",
      "Nimzowitsch was a pioneer of this aggressive approach for White.",
    ],
  },
  C03: {
    color: "black",
    style: "classical",
    character: "solid",
    complexity: "intermediate",
    family: "French Defence",
  },
  C04: {
    color: "black",
    style: "classical",
    character: "solid",
    complexity: "intermediate",
    family: "French Defence",
  },
  C05: {
    color: "black",
    style: "classical",
    character: "solid",
    complexity: "intermediate",
    family: "French Defence",
  },
  C06: {
    color: "black",
    style: "classical",
    character: "solid",
    complexity: "intermediate",
    family: "French Defence",
  },
  C07: {
    color: "black",
    style: "classical",
    character: "solid",
    complexity: "intermediate",
    family: "French Defence",
  },
  C08: {
    color: "black",
    style: "classical",
    character: "dynamic",
    complexity: "intermediate",
    family: "French Defence",
  },
  C09: {
    color: "black",
    style: "classical",
    character: "dynamic",
    complexity: "advanced",
    family: "French Defence",
  },
  C10: {
    color: "black",
    style: "classical",
    character: "solid",
    complexity: "intermediate",
    family: "French Defence",
  },
  C11: {
    color: "black",
    style: "classical",
    character: "solid",
    complexity: "intermediate",
    family: "French Defence",
    ideas: [
      "Classical French: ...Nf6 pins White to defending e4.",
      "Rich positional and tactical battles arise from this move order.",
    ],
  },
  C12: {
    color: "black",
    style: "classical",
    character: "dynamic",
    complexity: "advanced",
    family: "French Defence",
    ideas: [
      "MacCutcheon Variation: ...Bb4 pins the knight, creating complications.",
      "Black immediately unbalances the position with the pin.",
    ],
  },
  C13: {
    color: "black",
    style: "classical",
    character: "solid",
    complexity: "intermediate",
    family: "French Defence",
  },
  C14: {
    color: "black",
    style: "classical",
    character: "positional",
    complexity: "advanced",
    family: "French Defence",
    ideas: [
      "Classical French main line — deeply theoretical.",
      "White has a space advantage; Black seeks counterplay on the queenside.",
    ],
  },
  C15: {
    color: "black",
    style: "classical",
    character: "solid",
    complexity: "intermediate",
    family: "French Defence",
  },
  C16: {
    color: "black",
    style: "classical",
    character: "solid",
    complexity: "intermediate",
    family: "French Defence",
  },
  C17: {
    color: "black",
    style: "classical",
    character: "dynamic",
    complexity: "advanced",
    family: "French Defence",
  },
  C18: {
    color: "black",
    style: "classical",
    character: "dynamic",
    complexity: "advanced",
    family: "French Defence",
    ideas: [
      "French Winawer main line: ...Bb4 creates long-term imbalances.",
      "Black's bishop pair vs White's kingside pawn majority.",
      "One of the most theoretically rich variations in all of chess.",
    ],
  },
  C19: {
    color: "black",
    style: "classical",
    character: "aggressive",
    complexity: "advanced",
    family: "French Defence",
  },
  C20: {
    color: "white",
    style: "classical",
    character: "aggressive",
    complexity: "beginner",
    family: "King's Pawn",
    ideas: [
      "1.e4 e5 — the classic Open Game start.",
      "Both sides fight for the centre immediately.",
    ],
  },
  C21: {
    color: "white",
    style: "classical",
    character: "aggressive",
    complexity: "beginner",
    family: "King's Pawn",
    ideas: [
      "Centre Game: 2.d4 opens the centre immediately.",
      "White develops the queen early after 2...exd4 3.Qxd4.",
    ],
  },
  C22: {
    color: "white",
    style: "classical",
    character: "aggressive",
    complexity: "beginner",
    family: "King's Pawn",
  },
  C23: {
    color: "white",
    style: "classical",
    character: "aggressive",
    complexity: "beginner",
    family: "Bishop's Opening",
    ideas: [
      "Bishop's Opening: 2.Bc4 immediately targets f7.",
      "Avoids the Petrov while developing harmoniously.",
    ],
  },
  C24: {
    color: "white",
    style: "classical",
    character: "aggressive",
    complexity: "beginner",
    family: "Bishop's Opening",
  },
  C25: {
    color: "white",
    style: "classical",
    character: "tactical",
    complexity: "intermediate",
    family: "Vienna Game",
    ideas: [
      "Vienna Game: 2.Nc3 — solid development before any commitment.",
      "Can transpose to the Vienna Gambit with f4 for attacking play.",
    ],
  },
  C26: {
    color: "white",
    style: "classical",
    character: "positional",
    complexity: "intermediate",
    family: "Vienna Game",
  },
  C27: {
    color: "white",
    style: "classical",
    character: "tactical",
    complexity: "intermediate",
    family: "Vienna Game",
  },
  C28: {
    color: "white",
    style: "classical",
    character: "positional",
    complexity: "intermediate",
    family: "Vienna Game",
  },
  C29: {
    color: "white",
    style: "classical",
    character: "tactical",
    complexity: "intermediate",
    family: "Vienna Game",
  },
  C30: {
    color: "white",
    style: "classical",
    character: "aggressive",
    complexity: "intermediate",
    family: "King's Gambit",
    ideas: [
      "King's Gambit: 2.f4 — the most romantic opening in classical chess.",
      "White sacrifices a pawn for rapid development and attacking chances.",
      "Favoured by Fischer and the great 19th-century attacking masters.",
    ],
  },
  C31: {
    color: "white",
    style: "classical",
    character: "aggressive",
    complexity: "intermediate",
    family: "King's Gambit",
  },
  C32: {
    color: "white",
    style: "classical",
    character: "aggressive",
    complexity: "intermediate",
    family: "King's Gambit",
  },
  C33: {
    color: "white",
    style: "classical",
    character: "aggressive",
    complexity: "intermediate",
    family: "King's Gambit",
  },
  C34: {
    color: "white",
    style: "classical",
    character: "aggressive",
    complexity: "intermediate",
    family: "King's Gambit",
    ideas: [
      "King's Gambit Accepted main lines — White has the open f-file.",
      "Active piece play compensates for the sacrificed f4 pawn.",
    ],
  },
  C35: {
    color: "white",
    style: "classical",
    character: "aggressive",
    complexity: "intermediate",
    family: "King's Gambit",
  },
  C36: {
    color: "white",
    style: "classical",
    character: "aggressive",
    complexity: "intermediate",
    family: "King's Gambit",
  },
  C37: {
    color: "white",
    style: "classical",
    character: "aggressive",
    complexity: "advanced",
    family: "King's Gambit",
    ideas: [
      "Muzio Gambit — White sacrifices a knight for a fierce kingside attack.",
      "Extremely tactical; correct play is crucial for both sides.",
    ],
  },
  C38: {
    color: "white",
    style: "classical",
    character: "aggressive",
    complexity: "advanced",
    family: "King's Gambit",
  },
  C39: {
    color: "white",
    style: "classical",
    character: "aggressive",
    complexity: "advanced",
    family: "King's Gambit",
  },
  C40: {
    color: "white",
    style: "classical",
    character: "aggressive",
    complexity: "beginner",
    family: "King's Pawn",
  },
  C41: {
    color: "black",
    style: "classical",
    character: "solid",
    complexity: "intermediate",
    family: "Philidor Defence",
    ideas: [
      "Philidor Defence: 2...d6 — solid but slightly passive.",
      "Modern interpretations often see ...Nf6 and ...exd4 for activity.",
    ],
  },
  C42: {
    color: "black",
    style: "classical",
    character: "solid",
    complexity: "intermediate",
    family: "Petrov Defence",
    ideas: [
      "Petrov (Russian) Defence: 2...Nf6 mirrors White's knight.",
      "Extremely solid — a drawing weapon at the highest level.",
      "Avoiding complications; popular among players who want quiet games.",
    ],
  },
  C43: {
    color: "black",
    style: "classical",
    character: "solid",
    complexity: "intermediate",
    family: "Petrov Defence",
  },
  C44: {
    color: "white",
    style: "classical",
    character: "aggressive",
    complexity: "beginner",
    family: "King's Pawn",
    ideas: [
      "Scotch Opening gambit systems — active and direct.",
      "White aims to open lines quickly with d4.",
    ],
  },
  C45: {
    color: "white",
    style: "classical",
    character: "solid",
    complexity: "intermediate",
    family: "Scotch Game",
    ideas: [
      "Scotch Game: 3.d4 exd4 4.Nxd4 — Kasparov revived this classic.",
      "White has a slight lead in development and open lines.",
      "More forcing than the Italian; theory is extensive at the top level.",
    ],
  },
  C46: {
    color: "white",
    style: "classical",
    character: "positional",
    complexity: "beginner",
    family: "Three Knights / Four Knights",
    ideas: [
      "Three Knights: quick development; solid but unambitious for White.",
    ],
  },
  C47: {
    color: "white",
    style: "classical",
    character: "positional",
    complexity: "beginner",
    family: "Four Knights",
    ideas: [
      "Four Knights: symmetrical development — leads to balanced positions.",
    ],
  },
  C48: {
    color: "white",
    style: "classical",
    character: "positional",
    complexity: "intermediate",
    family: "Four Knights",
    ideas: [
      "Four Knights Spanish: Bb5 pin gives White a slight edge.",
    ],
  },
  C49: {
    color: "white",
    style: "classical",
    character: "positional",
    complexity: "intermediate",
    family: "Four Knights",
  },
  C50: {
    color: "white",
    style: "classical",
    character: "solid",
    complexity: "beginner",
    family: "Italian Game",
    ideas: [
      "Italian Game: Bc4 targets the weak f7 pawn.",
      "Classical development; extremely popular from beginner to grandmaster.",
    ],
  },
  C51: {
    color: "white",
    style: "classical",
    character: "aggressive",
    complexity: "intermediate",
    family: "Italian Game",
    ideas: [
      "Evans Gambit: 4.b4 sacrifices a pawn for a large centre.",
      "Morphy's and Chigorin's favourite weapon — romantic and attacking.",
    ],
  },
  C52: {
    color: "white",
    style: "classical",
    character: "aggressive",
    complexity: "intermediate",
    family: "Italian Game",
  },
  C53: {
    color: "white",
    style: "classical",
    character: "solid",
    complexity: "intermediate",
    family: "Italian Game",
    ideas: [
      "Classical Italian: d3, c3, Bb3 setup — solid positional play.",
      "White builds a strong but unforced position.",
    ],
  },
  C54: {
    color: "white",
    style: "classical",
    character: "solid",
    complexity: "intermediate",
    family: "Italian Game",
  },
  C55: {
    color: "white",
    style: "classical",
    character: "aggressive",
    complexity: "intermediate",
    family: "Italian Game",
  },
  C56: {
    color: "white",
    style: "classical",
    character: "aggressive",
    complexity: "intermediate",
    family: "Italian Game",
    ideas: [
      "Two Knights Defence: ...Nf6 challenges d4 instead of defending.",
      "Wild complications after 4.Ng5 d5 5.exd5.",
    ],
  },
  C57: {
    color: "white",
    style: "classical",
    character: "aggressive",
    complexity: "advanced",
    family: "Italian Game",
  },
  C58: {
    color: "white",
    style: "classical",
    character: "aggressive",
    complexity: "intermediate",
    family: "Italian Game",
  },
  C59: {
    color: "white",
    style: "classical",
    character: "aggressive",
    complexity: "advanced",
    family: "Italian Game",
  },
  C60: {
    color: "white",
    style: "classical",
    character: "positional",
    complexity: "intermediate",
    family: "Spanish (Ruy López)",
    ideas: [
      "Ruy López: 3.Bb5 pressures the e5 pawn indirectly.",
      "The most classical and enduring opening in chess history.",
      "White aims for a long-term positional advantage.",
    ],
  },
  C61: {
    color: "white",
    style: "classical",
    character: "positional",
    complexity: "intermediate",
    family: "Spanish (Ruy López)",
  },
  C62: {
    color: "white",
    style: "classical",
    character: "positional",
    complexity: "intermediate",
    family: "Spanish (Ruy López)",
  },
  C63: {
    color: "white",
    style: "classical",
    character: "dynamic",
    complexity: "intermediate",
    family: "Spanish (Ruy López)",
    ideas: [
      "Schliemann Defence: ...f5 immediately attacks e4.",
      "Sharp and tricky — White must respond carefully.",
    ],
  },
  C64: {
    color: "white",
    style: "classical",
    character: "positional",
    complexity: "intermediate",
    family: "Spanish (Ruy López)",
    ideas: [
      "Classical Defence: ...Bc5 — natural development.",
      "Less common than the Berlin or Morphy; leads to rich middlegames.",
    ],
  },
  C65: {
    color: "white",
    style: "classical",
    character: "solid",
    complexity: "intermediate",
    family: "Spanish (Ruy López)",
    ideas: [
      "Berlin Defence: 3...Nf6 — the modern drawing weapon of choice.",
      "After the Berlin endgame, Black has structural compensation.",
      "Popularised by Kramnik in the 2000 World Championship.",
    ],
  },
  C66: {
    color: "white",
    style: "classical",
    character: "positional",
    complexity: "intermediate",
    family: "Spanish (Ruy López)",
  },
  C67: {
    color: "white",
    style: "classical",
    character: "solid",
    complexity: "advanced",
    family: "Spanish (Ruy López)",
    ideas: [
      "Berlin Endgame: ...Nxe4 leads to a queenless middlegame.",
      "Black has an extra e-pawn in the endgame; White has the initiative.",
    ],
  },
  C68: {
    color: "white",
    style: "classical",
    character: "positional",
    complexity: "intermediate",
    family: "Spanish (Ruy López)",
    ideas: [
      "Exchange Variation: White captures on c6, doubling Black's pawns.",
      "Positional advantage: White's pawn structure is superior.",
    ],
  },
  C69: {
    color: "white",
    style: "classical",
    character: "positional",
    complexity: "intermediate",
    family: "Spanish (Ruy López)",
  },
  C70: {
    color: "white",
    style: "classical",
    character: "positional",
    complexity: "intermediate",
    family: "Spanish (Ruy López)",
  },
  C71: {
    color: "white",
    style: "classical",
    character: "positional",
    complexity: "intermediate",
    family: "Spanish (Ruy López)",
  },
  C72: {
    color: "white",
    style: "classical",
    character: "positional",
    complexity: "intermediate",
    family: "Spanish (Ruy López)",
  },
  C73: {
    color: "white",
    style: "classical",
    character: "positional",
    complexity: "intermediate",
    family: "Spanish (Ruy López)",
  },
  C74: {
    color: "white",
    style: "classical",
    character: "positional",
    complexity: "intermediate",
    family: "Spanish (Ruy López)",
  },
  C75: {
    color: "white",
    style: "classical",
    character: "positional",
    complexity: "intermediate",
    family: "Spanish (Ruy López)",
  },
  C76: {
    color: "white",
    style: "classical",
    character: "positional",
    complexity: "intermediate",
    family: "Spanish (Ruy López)",
  },
  C77: {
    color: "white",
    style: "classical",
    character: "positional",
    complexity: "intermediate",
    family: "Spanish (Ruy López)",
  },
  C78: {
    color: "white",
    style: "classical",
    character: "positional",
    complexity: "intermediate",
    family: "Spanish (Ruy López)",
  },
  C79: {
    color: "white",
    style: "classical",
    character: "positional",
    complexity: "intermediate",
    family: "Spanish (Ruy López)",
  },
  C80: {
    color: "white",
    style: "classical",
    character: "dynamic",
    complexity: "advanced",
    family: "Spanish (Ruy López)",
    ideas: [
      "Open Spanish: ...Nxe4 gives Black immediate counterplay.",
      "Sharp and theoretical; needs precise preparation.",
    ],
  },
  C81: {
    color: "white",
    style: "classical",
    character: "aggressive",
    complexity: "advanced",
    family: "Spanish (Ruy López)",
  },
  C82: {
    color: "white",
    style: "classical",
    character: "dynamic",
    complexity: "advanced",
    family: "Spanish (Ruy López)",
  },
  C83: {
    color: "white",
    style: "classical",
    character: "dynamic",
    complexity: "advanced",
    family: "Spanish (Ruy López)",
  },
  C84: {
    color: "white",
    style: "classical",
    character: "positional",
    complexity: "intermediate",
    family: "Spanish (Ruy López)",
  },
  C85: {
    color: "white",
    style: "classical",
    character: "positional",
    complexity: "intermediate",
    family: "Spanish (Ruy López)",
  },
  C86: {
    color: "white",
    style: "classical",
    character: "positional",
    complexity: "advanced",
    family: "Spanish (Ruy López)",
  },
  C87: {
    color: "white",
    style: "classical",
    character: "positional",
    complexity: "advanced",
    family: "Spanish (Ruy López)",
  },
  C88: {
    color: "white",
    style: "classical",
    character: "positional",
    complexity: "advanced",
    family: "Spanish (Ruy López)",
    ideas: [
      "Closed Spanish main line: the most theoretically dense system.",
      "Both sides manoeuvre for decades trying to create winning chances.",
      "Karpov dominated this system throughout the 1970s and 1980s.",
    ],
  },
  C89: {
    color: "white",
    style: "classical",
    character: "dynamic",
    complexity: "advanced",
    family: "Spanish (Ruy López)",
    ideas: [
      "Marshall Attack: Black sacrifices a pawn for lasting initiative.",
      "...e5-e4 launches a queen-led kingside attack.",
      "One of the most romantically bold gambits in modern theory.",
    ],
  },
  C90: {
    color: "white",
    style: "classical",
    character: "positional",
    complexity: "advanced",
    family: "Spanish (Ruy López)",
  },
  C91: {
    color: "white",
    style: "classical",
    character: "positional",
    complexity: "advanced",
    family: "Spanish (Ruy López)",
  },
  C92: {
    color: "white",
    style: "classical",
    character: "positional",
    complexity: "advanced",
    family: "Spanish (Ruy López)",
  },
  C93: {
    color: "white",
    style: "classical",
    character: "positional",
    complexity: "advanced",
    family: "Spanish (Ruy López)",
  },
  C94: {
    color: "white",
    style: "classical",
    character: "positional",
    complexity: "advanced",
    family: "Spanish (Ruy López)",
  },
  C95: {
    color: "white",
    style: "classical",
    character: "positional",
    complexity: "advanced",
    family: "Spanish (Ruy López)",
  },
  C96: {
    color: "white",
    style: "classical",
    character: "positional",
    complexity: "advanced",
    family: "Spanish (Ruy López)",
  },
  C97: {
    color: "white",
    style: "classical",
    character: "positional",
    complexity: "advanced",
    family: "Spanish (Ruy López)",
  },
  C98: {
    color: "white",
    style: "classical",
    character: "positional",
    complexity: "advanced",
    family: "Spanish (Ruy López)",
  },
  C99: {
    color: "white",
    style: "classical",
    character: "positional",
    complexity: "advanced",
    family: "Spanish (Ruy López)",
  },

  // ─── D: Closed games, Queen's Gambit ─────────────────────────────────────
  D00: {
    color: "white",
    style: "classical",
    character: "positional",
    complexity: "beginner",
    family: "Queen's Pawn",
    ideas: [
      "1.d4 d5 — classical closed game.",
      "White aims for a Queen's Gambit formation.",
    ],
  },
  D01: {
    color: "white",
    style: "classical",
    character: "positional",
    complexity: "intermediate",
    family: "Queen's Pawn",
    ideas: [
      "Richter-Veresov Attack: Nc3 + Bg5 pins the knight early.",
      "Aggressive and somewhat tricky; avoids main-line Queen's Gambit theory.",
    ],
  },
  D02: {
    color: "white",
    style: "modern",
    character: "positional",
    complexity: "beginner",
    family: "Queen's Pawn",
  },
  D03: {
    color: "white",
    style: "modern",
    character: "positional",
    complexity: "intermediate",
    family: "Torre Attack",
    ideas: [
      "Torre Attack: Nf3+d4+Bg5 — solid and slightly aggressive.",
      "Avoids highly theoretical lines; popular at club level.",
    ],
  },
  D04: {
    color: "white",
    style: "classical",
    character: "solid",
    complexity: "beginner",
    family: "Queen's Pawn",
  },
  D05: {
    color: "white",
    style: "classical",
    character: "solid",
    complexity: "intermediate",
    family: "Colle System",
    ideas: [
      "Colle System: d4+Nf3+e3+Bd3 — reliable and solid.",
      "Builds slowly; often aims for a kingside attack with e4.",
    ],
  },
  D06: {
    color: "white",
    style: "classical",
    character: "positional",
    complexity: "beginner",
    family: "Queen's Gambit",
  },
  D07: {
    color: "black",
    style: "classical",
    character: "solid",
    complexity: "intermediate",
    family: "Queen's Gambit",
    ideas: [
      "Chigorin Defence: 2...Nc6 — unorthodox but active.",
      "Black fights for e4 and accepts potential pawn structure weaknesses.",
    ],
  },
  D08: {
    color: "black",
    style: "classical",
    character: "aggressive",
    complexity: "intermediate",
    family: "Queen's Gambit",
    ideas: [
      "Albin Counter-Gambit: 2...e5 — sharp pawn sacrifice.",
      "Black gains counterplay but faces lasting structural weakness.",
    ],
  },
  D09: {
    color: "black",
    style: "classical",
    character: "aggressive",
    complexity: "intermediate",
    family: "Queen's Gambit",
  },
  D10: {
    color: "white",
    style: "classical",
    character: "positional",
    complexity: "intermediate",
    family: "Queen's Gambit",
    ideas: [
      "Slav Defence: 2...c6 — the most solid response to the Queen's Gambit.",
      "Black defends d5 with a pawn, avoiding the isolated queen's pawn.",
    ],
  },
  D11: {
    color: "white",
    style: "classical",
    character: "solid",
    complexity: "intermediate",
    family: "Queen's Gambit",
  },
  D12: {
    color: "white",
    style: "classical",
    character: "solid",
    complexity: "intermediate",
    family: "Slav Defence",
    ideas: [
      "Slav Defence Exchange: White simplifies and aims for small edge.",
    ],
  },
  D13: {
    color: "white",
    style: "classical",
    character: "solid",
    complexity: "intermediate",
    family: "Slav Defence",
  },
  D14: {
    color: "white",
    style: "classical",
    character: "solid",
    complexity: "intermediate",
    family: "Slav Defence",
  },
  D15: {
    color: "white",
    style: "classical",
    character: "solid",
    complexity: "intermediate",
    family: "Slav Defence",
  },
  D16: {
    color: "white",
    style: "classical",
    character: "positional",
    complexity: "advanced",
    family: "Slav Defence",
  },
  D17: {
    color: "white",
    style: "classical",
    character: "dynamic",
    complexity: "advanced",
    family: "Slav Defence",
    ideas: [
      "Slav Defence with Bf4 — White claims strong bishop pair.",
      "Black must find precise counterplay to solve the opening problems.",
    ],
  },
  D18: {
    color: "white",
    style: "classical",
    character: "dynamic",
    complexity: "advanced",
    family: "Slav Defence",
  },
  D19: {
    color: "white",
    style: "classical",
    character: "dynamic",
    complexity: "advanced",
    family: "Slav Defence",
  },
  D20: {
    color: "white",
    style: "classical",
    character: "aggressive",
    complexity: "intermediate",
    family: "Queen's Gambit Accepted",
    ideas: [
      "QGA: Black accepts the gambit pawn and must return it or develop actively.",
      "Leads to open, dynamic positions with White's active pieces.",
      "A favourite of players who want to fight for the initiative from move one.",
    ],
  },
  D21: {
    color: "white",
    style: "classical",
    character: "dynamic",
    complexity: "intermediate",
    family: "Queen's Gambit Accepted",
  },
  D22: {
    color: "white",
    style: "classical",
    character: "dynamic",
    complexity: "intermediate",
    family: "Queen's Gambit Accepted",
  },
  D23: {
    color: "white",
    style: "classical",
    character: "dynamic",
    complexity: "intermediate",
    family: "Queen's Gambit Accepted",
  },
  D24: {
    color: "white",
    style: "classical",
    character: "dynamic",
    complexity: "intermediate",
    family: "Queen's Gambit Accepted",
  },
  D25: {
    color: "white",
    style: "classical",
    character: "dynamic",
    complexity: "intermediate",
    family: "Queen's Gambit Accepted",
  },
  D26: {
    color: "white",
    style: "classical",
    character: "positional",
    complexity: "intermediate",
    family: "Queen's Gambit Accepted",
  },
  D27: {
    color: "white",
    style: "classical",
    character: "positional",
    complexity: "intermediate",
    family: "Queen's Gambit Accepted",
  },
  D28: {
    color: "white",
    style: "classical",
    character: "positional",
    complexity: "advanced",
    family: "Queen's Gambit Accepted",
  },
  D29: {
    color: "white",
    style: "classical",
    character: "positional",
    complexity: "advanced",
    family: "Queen's Gambit Accepted",
  },
  D30: {
    color: "white",
    style: "classical",
    character: "positional",
    complexity: "intermediate",
    family: "Queen's Gambit Declined",
    ideas: [
      "QGD: Black declines the gambit and builds a solid structure.",
      "One of the most enduring openings in chess history.",
      "Black aims for eventual ...c5 or ...e5 to liberate the position.",
    ],
  },
  D31: {
    color: "white",
    style: "classical",
    character: "positional",
    complexity: "intermediate",
    family: "Queen's Gambit Declined",
  },
  D32: {
    color: "white",
    style: "classical",
    character: "positional",
    complexity: "intermediate",
    family: "Tarrasch Defence",
    ideas: [
      "Tarrasch Defence: 2...e6 3.Nc3 c5 — active counterplay with an IQP.",
      "Black gets piece activity and counterplay in exchange for a long-term weakness.",
    ],
  },
  D33: {
    color: "white",
    style: "classical",
    character: "dynamic",
    complexity: "advanced",
    family: "Tarrasch Defence",
  },
  D34: {
    color: "white",
    style: "classical",
    character: "dynamic",
    complexity: "advanced",
    family: "Tarrasch Defence",
  },
  D35: {
    color: "white",
    style: "classical",
    character: "positional",
    complexity: "intermediate",
    family: "Queen's Gambit Declined",
  },
  D36: {
    color: "white",
    style: "classical",
    character: "positional",
    complexity: "intermediate",
    family: "Queen's Gambit Declined",
  },
  D37: {
    color: "white",
    style: "classical",
    character: "positional",
    complexity: "intermediate",
    family: "Queen's Gambit Declined",
  },
  D38: {
    color: "white",
    style: "classical",
    character: "positional",
    complexity: "intermediate",
    family: "Queen's Gambit Declined",
  },
  D39: {
    color: "white",
    style: "classical",
    character: "dynamic",
    complexity: "advanced",
    family: "Queen's Gambit Declined",
  },
  D40: {
    color: "white",
    style: "classical",
    character: "positional",
    complexity: "intermediate",
    family: "Queen's Gambit Declined",
  },
  D41: {
    color: "white",
    style: "classical",
    character: "positional",
    complexity: "intermediate",
    family: "Queen's Gambit Declined",
  },
  D42: {
    color: "white",
    style: "classical",
    character: "positional",
    complexity: "advanced",
    family: "Queen's Gambit Declined",
  },
  D43: {
    color: "white",
    style: "classical",
    character: "dynamic",
    complexity: "advanced",
    family: "Semi-Slav Defence",
    ideas: [
      "Semi-Slav: ...c6+...e6 — the most theoretically demanding system in QGD.",
      "Black combines the ideas of the Slav and the QGD.",
      "Extremely rich theory; the Meran, Moscow, and Anti-Moscow are sub-systems.",
    ],
  },
  D44: {
    color: "white",
    style: "classical",
    character: "aggressive",
    complexity: "advanced",
    family: "Semi-Slav Defence",
    ideas: [
      "Anti-Meran Gambit: sharp pawn sacrifices and double-edged positions.",
    ],
  },
  D45: {
    color: "white",
    style: "classical",
    character: "dynamic",
    complexity: "advanced",
    family: "Semi-Slav Defence",
  },
  D46: {
    color: "white",
    style: "classical",
    character: "positional",
    complexity: "advanced",
    family: "Semi-Slav Defence",
  },
  D47: {
    color: "white",
    style: "classical",
    character: "dynamic",
    complexity: "advanced",
    family: "Semi-Slav Defence",
    ideas: [
      "Meran Variation: ...dxc4 frees the bishops and creates pawn tension.",
      "Some of the sharpest positions in closed-game theory.",
    ],
  },
  D48: {
    color: "white",
    style: "classical",
    character: "dynamic",
    complexity: "advanced",
    family: "Semi-Slav Defence",
  },
  D49: {
    color: "white",
    style: "classical",
    character: "aggressive",
    complexity: "advanced",
    family: "Semi-Slav Defence",
  },
  D50: {
    color: "white",
    style: "classical",
    character: "positional",
    complexity: "intermediate",
    family: "Queen's Gambit Declined",
  },
  D51: {
    color: "white",
    style: "classical",
    character: "positional",
    complexity: "intermediate",
    family: "Queen's Gambit Declined",
  },
  D52: {
    color: "white",
    style: "classical",
    character: "positional",
    complexity: "intermediate",
    family: "Cambridge Springs",
    ideas: [
      "Cambridge Springs Variation: ...Qa5 — Black pressures White's Nc3.",
      "Old-fashioned but still solid; creates immediate queen activity.",
    ],
  },
  D53: {
    color: "white",
    style: "classical",
    character: "positional",
    complexity: "intermediate",
    family: "Queen's Gambit Declined",
  },
  D54: {
    color: "white",
    style: "classical",
    character: "positional",
    complexity: "intermediate",
    family: "Queen's Gambit Declined",
  },
  D55: {
    color: "white",
    style: "classical",
    character: "positional",
    complexity: "intermediate",
    family: "Queen's Gambit Declined",
  },
  D56: {
    color: "white",
    style: "classical",
    character: "positional",
    complexity: "advanced",
    family: "Queen's Gambit Declined",
  },
  D57: {
    color: "white",
    style: "classical",
    character: "positional",
    complexity: "advanced",
    family: "Queen's Gambit Declined",
  },
  D58: {
    color: "white",
    style: "classical",
    character: "positional",
    complexity: "advanced",
    family: "Tartakower Defence",
    ideas: [
      "Tartakower Defence: ...b6 fianchettoes the bishop.",
      "Petrosian and Kramnik's weapon; solid and reliable.",
    ],
  },
  D59: {
    color: "white",
    style: "classical",
    character: "positional",
    complexity: "advanced",
    family: "Queen's Gambit Declined",
  },
  D60: {
    color: "white",
    style: "classical",
    character: "positional",
    complexity: "intermediate",
    family: "Queen's Gambit Declined",
  },
  D61: {
    color: "white",
    style: "classical",
    character: "positional",
    complexity: "intermediate",
    family: "Queen's Gambit Declined",
  },
  D62: {
    color: "white",
    style: "classical",
    character: "positional",
    complexity: "intermediate",
    family: "Queen's Gambit Declined",
  },
  D63: {
    color: "white",
    style: "classical",
    character: "positional",
    complexity: "intermediate",
    family: "Queen's Gambit Declined",
    ideas: [
      "Orthodox QGD: the central and most classical line.",
      "White builds up slowly with Nf3, Bd3, and castles short.",
    ],
  },
  D70: {
    color: "black",
    style: "hypermodern",
    character: "dynamic",
    complexity: "advanced",
    family: "Grünfeld Defence",
    ideas: [
      "Grünfeld Defence: ...d5 vs White's e4+d4 centre — then attacks it.",
      "Black allows White a large centre only to undermine it with pieces.",
      "Extremely theoretical; a favourite of Fischer, Kasparov, and Spassky.",
    ],
  },
  D71: {
    color: "black",
    style: "hypermodern",
    character: "dynamic",
    complexity: "advanced",
    family: "Grünfeld Defence",
  },
  D72: {
    color: "black",
    style: "hypermodern",
    character: "dynamic",
    complexity: "advanced",
    family: "Grünfeld Defence",
  },
  D73: {
    color: "black",
    style: "hypermodern",
    character: "dynamic",
    complexity: "advanced",
    family: "Grünfeld Defence",
  },
  D74: {
    color: "black",
    style: "hypermodern",
    character: "dynamic",
    complexity: "advanced",
    family: "Grünfeld Defence",
  },
  D75: {
    color: "black",
    style: "hypermodern",
    character: "dynamic",
    complexity: "advanced",
    family: "Grünfeld Defence",
  },
  D76: {
    color: "black",
    style: "hypermodern",
    character: "dynamic",
    complexity: "advanced",
    family: "Grünfeld Defence",
  },
  D77: {
    color: "black",
    style: "hypermodern",
    character: "dynamic",
    complexity: "advanced",
    family: "Grünfeld Defence",
  },
  D78: {
    color: "black",
    style: "hypermodern",
    character: "dynamic",
    complexity: "advanced",
    family: "Grünfeld Defence",
  },
  D79: {
    color: "black",
    style: "hypermodern",
    character: "dynamic",
    complexity: "advanced",
    family: "Grünfeld Defence",
  },
  D80: {
    color: "black",
    style: "hypermodern",
    character: "dynamic",
    complexity: "advanced",
    family: "Grünfeld Defence",
  },
  D81: {
    color: "black",
    style: "hypermodern",
    character: "aggressive",
    complexity: "advanced",
    family: "Grünfeld Defence",
  },
  D82: {
    color: "black",
    style: "hypermodern",
    character: "dynamic",
    complexity: "advanced",
    family: "Grünfeld Defence",
  },
  D83: {
    color: "black",
    style: "hypermodern",
    character: "aggressive",
    complexity: "advanced",
    family: "Grünfeld Defence",
  },
  D84: {
    color: "black",
    style: "hypermodern",
    character: "aggressive",
    complexity: "advanced",
    family: "Grünfeld Defence",
  },
  D85: {
    color: "black",
    style: "hypermodern",
    character: "dynamic",
    complexity: "advanced",
    family: "Grünfeld Defence",
    ideas: [
      "Exchange Grünfeld: White plays cxd5+Nxc3+ with Bc4/Be3.",
      "One of the most theoretically important modern battlefields.",
    ],
  },
  D86: {
    color: "black",
    style: "hypermodern",
    character: "dynamic",
    complexity: "advanced",
    family: "Grünfeld Defence",
  },
  D87: {
    color: "black",
    style: "hypermodern",
    character: "dynamic",
    complexity: "advanced",
    family: "Grünfeld Defence",
  },
  D88: {
    color: "black",
    style: "hypermodern",
    character: "aggressive",
    complexity: "advanced",
    family: "Grünfeld Defence",
  },
  D89: {
    color: "black",
    style: "hypermodern",
    character: "aggressive",
    complexity: "advanced",
    family: "Grünfeld Defence",
  },
  D90: {
    color: "black",
    style: "hypermodern",
    character: "dynamic",
    complexity: "advanced",
    family: "Grünfeld Defence",
  },
  D91: {
    color: "black",
    style: "hypermodern",
    character: "dynamic",
    complexity: "advanced",
    family: "Grünfeld Defence",
  },
  D92: {
    color: "black",
    style: "hypermodern",
    character: "dynamic",
    complexity: "advanced",
    family: "Grünfeld Defence",
  },
  D93: {
    color: "black",
    style: "hypermodern",
    character: "dynamic",
    complexity: "advanced",
    family: "Grünfeld Defence",
  },
  D94: {
    color: "black",
    style: "hypermodern",
    character: "solid",
    complexity: "advanced",
    family: "Grünfeld Defence",
  },
  D95: {
    color: "black",
    style: "hypermodern",
    character: "dynamic",
    complexity: "advanced",
    family: "Grünfeld Defence",
  },
  D96: {
    color: "black",
    style: "hypermodern",
    character: "dynamic",
    complexity: "advanced",
    family: "Grünfeld Defence",
  },
  D97: {
    color: "black",
    style: "hypermodern",
    character: "aggressive",
    complexity: "advanced",
    family: "Grünfeld Defence",
  },
  D98: {
    color: "black",
    style: "hypermodern",
    character: "aggressive",
    complexity: "advanced",
    family: "Grünfeld Defence",
  },
  D99: {
    color: "black",
    style: "hypermodern",
    character: "aggressive",
    complexity: "advanced",
    family: "Grünfeld Defence",
  },

  // ─── E: Indian Defences ──────────────────────────────────────────────────
  E00: {
    color: "white",
    style: "modern",
    character: "positional",
    complexity: "intermediate",
    family: "Catalan",
    ideas: [
      "Catalan Opening: g3+Bg2 — fianchetto combined with Queen's Gambit.",
      "White gets enduring pressure along the c1-h8 diagonal.",
      "Karpov and Kramnik used this to grind out wins in tight positions.",
    ],
  },
  E01: {
    color: "white",
    style: "modern",
    character: "positional",
    complexity: "intermediate",
    family: "Catalan",
  },
  E02: {
    color: "white",
    style: "modern",
    character: "positional",
    complexity: "intermediate",
    family: "Catalan",
  },
  E03: {
    color: "white",
    style: "modern",
    character: "positional",
    complexity: "intermediate",
    family: "Catalan",
  },
  E04: {
    color: "white",
    style: "modern",
    character: "positional",
    complexity: "advanced",
    family: "Catalan",
  },
  E05: {
    color: "white",
    style: "modern",
    character: "positional",
    complexity: "advanced",
    family: "Catalan",
  },
  E06: {
    color: "white",
    style: "modern",
    character: "positional",
    complexity: "advanced",
    family: "Catalan",
  },
  E07: {
    color: "white",
    style: "modern",
    character: "positional",
    complexity: "advanced",
    family: "Catalan",
  },
  E08: {
    color: "white",
    style: "modern",
    character: "positional",
    complexity: "advanced",
    family: "Catalan",
  },
  E09: {
    color: "white",
    style: "modern",
    character: "positional",
    complexity: "advanced",
    family: "Catalan",
    ideas: [
      "Catalan main line: Black has kept the c4 pawn.",
      "Long-term pressure on the d5 pawn; White converts positional pressure to material.",
    ],
  },
  E10: {
    color: "black",
    style: "modern",
    character: "solid",
    complexity: "intermediate",
    family: "Indian Defences",
    ideas: [
      "Anti-Queen's Indian systems — various setups for both sides.",
    ],
  },
  E11: {
    color: "black",
    style: "modern",
    character: "solid",
    complexity: "intermediate",
    family: "Bogo-Indian Defence",
    ideas: [
      "Bogo-Indian: ...Bb4+ — an early check to disrupt White's plans.",
      "Solid but less theoretically demanding than the Nimzo-Indian.",
    ],
  },
  E12: {
    color: "black",
    style: "modern",
    character: "positional",
    complexity: "intermediate",
    family: "Queen's Indian Defence",
    ideas: [
      "Queen's Indian: ...b6 fianchettoes the bishop on b7.",
      "Hypermodern approach: the b7 bishop controls e4 indirectly.",
      "Petrosian and Kasparov used this to great effect.",
    ],
  },
  E13: {
    color: "black",
    style: "modern",
    character: "positional",
    complexity: "intermediate",
    family: "Queen's Indian Defence",
  },
  E14: {
    color: "black",
    style: "modern",
    character: "positional",
    complexity: "intermediate",
    family: "Queen's Indian Defence",
  },
  E15: {
    color: "black",
    style: "modern",
    character: "positional",
    complexity: "advanced",
    family: "Queen's Indian Defence",
    ideas: [
      "Main line QID: ...Bb7 + ...Be7 — the most classical approach.",
    ],
  },
  E16: {
    color: "black",
    style: "modern",
    character: "positional",
    complexity: "advanced",
    family: "Queen's Indian Defence",
  },
  E17: {
    color: "black",
    style: "modern",
    character: "positional",
    complexity: "advanced",
    family: "Queen's Indian Defence",
  },
  E18: {
    color: "black",
    style: "modern",
    character: "dynamic",
    complexity: "advanced",
    family: "Queen's Indian Defence",
  },
  E19: {
    color: "black",
    style: "modern",
    character: "dynamic",
    complexity: "advanced",
    family: "Queen's Indian Defence",
  },
  E20: {
    color: "black",
    style: "modern",
    character: "dynamic",
    complexity: "intermediate",
    family: "Nimzo-Indian Defence",
    ideas: [
      "Nimzo-Indian Defence: ...Bb4 pins the Nc3 and battles for e4.",
      "One of the most theoretically rich openings in all of chess.",
      "Invented by Nimzowitsch; Kasparov and Fischer championed it.",
      "Black accepts structural imbalances (doubled pawns) for the bishop pair.",
    ],
  },
  E21: {
    color: "black",
    style: "modern",
    character: "dynamic",
    complexity: "intermediate",
    family: "Nimzo-Indian Defence",
  },
  E22: {
    color: "black",
    style: "modern",
    character: "positional",
    complexity: "intermediate",
    family: "Nimzo-Indian Defence",
  },
  E23: {
    color: "black",
    style: "modern",
    character: "dynamic",
    complexity: "intermediate",
    family: "Nimzo-Indian Defence",
  },
  E24: {
    color: "black",
    style: "modern",
    character: "dynamic",
    complexity: "intermediate",
    family: "Nimzo-Indian Defence",
  },
  E25: {
    color: "black",
    style: "modern",
    character: "aggressive",
    complexity: "advanced",
    family: "Nimzo-Indian Defence",
    ideas: [
      "Sämisch Variation: 4.a3 + f3 — White attacks aggressively.",
      "Extremely sharp; Black must play precisely to survive.",
    ],
  },
  E26: {
    color: "black",
    style: "modern",
    character: "dynamic",
    complexity: "advanced",
    family: "Nimzo-Indian Defence",
  },
  E27: {
    color: "black",
    style: "modern",
    character: "dynamic",
    complexity: "advanced",
    family: "Nimzo-Indian Defence",
  },
  E28: {
    color: "black",
    style: "modern",
    character: "dynamic",
    complexity: "advanced",
    family: "Nimzo-Indian Defence",
  },
  E29: {
    color: "black",
    style: "modern",
    character: "aggressive",
    complexity: "advanced",
    family: "Nimzo-Indian Defence",
  },
  E30: {
    color: "black",
    style: "modern",
    character: "dynamic",
    complexity: "intermediate",
    family: "Nimzo-Indian Defence",
  },
  E31: {
    color: "black",
    style: "modern",
    character: "dynamic",
    complexity: "intermediate",
    family: "Nimzo-Indian Defence",
  },
  E32: {
    color: "black",
    style: "modern",
    character: "positional",
    complexity: "intermediate",
    family: "Nimzo-Indian Defence",
    ideas: [
      "Classical Variation: 4.Qc2 — avoids doubled pawns entirely.",
      "Popular at the top level; Karpov frequently chose this for White.",
    ],
  },
  E33: {
    color: "black",
    style: "modern",
    character: "positional",
    complexity: "intermediate",
    family: "Nimzo-Indian Defence",
  },
  E34: {
    color: "black",
    style: "modern",
    character: "dynamic",
    complexity: "advanced",
    family: "Nimzo-Indian Defence",
  },
  E35: {
    color: "black",
    style: "modern",
    character: "dynamic",
    complexity: "advanced",
    family: "Nimzo-Indian Defence",
  },
  E36: {
    color: "black",
    style: "modern",
    character: "dynamic",
    complexity: "advanced",
    family: "Nimzo-Indian Defence",
  },
  E37: {
    color: "black",
    style: "modern",
    character: "dynamic",
    complexity: "advanced",
    family: "Nimzo-Indian Defence",
  },
  E38: {
    color: "black",
    style: "modern",
    character: "dynamic",
    complexity: "advanced",
    family: "Nimzo-Indian Defence",
  },
  E39: {
    color: "black",
    style: "modern",
    character: "dynamic",
    complexity: "advanced",
    family: "Nimzo-Indian Defence",
  },
  E40: {
    color: "black",
    style: "modern",
    character: "dynamic",
    complexity: "intermediate",
    family: "Nimzo-Indian Defence",
  },
  E41: {
    color: "black",
    style: "modern",
    character: "dynamic",
    complexity: "intermediate",
    family: "Nimzo-Indian Defence",
  },
  E42: {
    color: "black",
    style: "modern",
    character: "dynamic",
    complexity: "advanced",
    family: "Nimzo-Indian Defence",
  },
  E43: {
    color: "black",
    style: "modern",
    character: "dynamic",
    complexity: "advanced",
    family: "Nimzo-Indian Defence",
  },
  E44: {
    color: "black",
    style: "modern",
    character: "dynamic",
    complexity: "advanced",
    family: "Nimzo-Indian Defence",
  },
  E45: {
    color: "black",
    style: "modern",
    character: "dynamic",
    complexity: "advanced",
    family: "Nimzo-Indian Defence",
  },
  E46: {
    color: "black",
    style: "modern",
    character: "solid",
    complexity: "advanced",
    family: "Nimzo-Indian Defence",
  },
  E47: {
    color: "black",
    style: "modern",
    character: "positional",
    complexity: "advanced",
    family: "Nimzo-Indian Defence",
  },
  E48: {
    color: "black",
    style: "modern",
    character: "positional",
    complexity: "advanced",
    family: "Nimzo-Indian Defence",
  },
  E49: {
    color: "black",
    style: "modern",
    character: "dynamic",
    complexity: "advanced",
    family: "Nimzo-Indian Defence",
  },
  E50: {
    color: "black",
    style: "modern",
    character: "dynamic",
    complexity: "intermediate",
    family: "Nimzo-Indian Defence",
  },
  E51: {
    color: "black",
    style: "modern",
    character: "dynamic",
    complexity: "intermediate",
    family: "Nimzo-Indian Defence",
  },
  E52: {
    color: "black",
    style: "modern",
    character: "dynamic",
    complexity: "advanced",
    family: "Nimzo-Indian Defence",
  },
  E53: {
    color: "black",
    style: "modern",
    character: "dynamic",
    complexity: "advanced",
    family: "Nimzo-Indian Defence",
  },
  E54: {
    color: "black",
    style: "modern",
    character: "dynamic",
    complexity: "advanced",
    family: "Nimzo-Indian Defence",
  },
  E55: {
    color: "black",
    style: "modern",
    character: "dynamic",
    complexity: "advanced",
    family: "Nimzo-Indian Defence",
  },
  E56: {
    color: "black",
    style: "modern",
    character: "dynamic",
    complexity: "advanced",
    family: "Nimzo-Indian Defence",
  },
  E57: {
    color: "black",
    style: "modern",
    character: "dynamic",
    complexity: "advanced",
    family: "Nimzo-Indian Defence",
  },
  E58: {
    color: "black",
    style: "modern",
    character: "dynamic",
    complexity: "advanced",
    family: "Nimzo-Indian Defence",
  },
  E59: {
    color: "black",
    style: "modern",
    character: "dynamic",
    complexity: "advanced",
    family: "Nimzo-Indian Defence",
  },
  E60: {
    color: "black",
    style: "modern",
    character: "dynamic",
    complexity: "intermediate",
    family: "King's Indian Defence",
    ideas: [
      "King's Indian Defence: Black fianchettoes to g7 and often plays ...e5.",
      "Black allows White a centre and then dynamically counterattacks.",
      "An extremely popular and combative choice at all levels.",
    ],
  },
  E61: {
    color: "black",
    style: "modern",
    character: "dynamic",
    complexity: "intermediate",
    family: "King's Indian Defence",
  },
  E62: {
    color: "black",
    style: "modern",
    character: "dynamic",
    complexity: "intermediate",
    family: "King's Indian Defence",
  },
  E63: {
    color: "black",
    style: "modern",
    character: "dynamic",
    complexity: "intermediate",
    family: "King's Indian Defence",
  },
  E64: {
    color: "black",
    style: "modern",
    character: "dynamic",
    complexity: "intermediate",
    family: "King's Indian Defence",
  },
  E65: {
    color: "black",
    style: "modern",
    character: "dynamic",
    complexity: "intermediate",
    family: "King's Indian Defence",
  },
  E66: {
    color: "black",
    style: "modern",
    character: "dynamic",
    complexity: "advanced",
    family: "King's Indian Defence",
  },
  E67: {
    color: "black",
    style: "modern",
    character: "dynamic",
    complexity: "advanced",
    family: "King's Indian Defence",
  },
  E68: {
    color: "black",
    style: "modern",
    character: "dynamic",
    complexity: "advanced",
    family: "King's Indian Defence",
  },
  E69: {
    color: "black",
    style: "modern",
    character: "dynamic",
    complexity: "advanced",
    family: "King's Indian Defence",
  },
  E70: {
    color: "black",
    style: "modern",
    character: "aggressive",
    complexity: "advanced",
    family: "King's Indian Defence",
  },
  E71: {
    color: "black",
    style: "modern",
    character: "aggressive",
    complexity: "advanced",
    family: "King's Indian Defence",
  },
  E72: {
    color: "black",
    style: "modern",
    character: "aggressive",
    complexity: "advanced",
    family: "King's Indian Defence",
  },
  E73: {
    color: "black",
    style: "modern",
    character: "solid",
    complexity: "advanced",
    family: "King's Indian Defence",
  },
  E74: {
    color: "black",
    style: "modern",
    character: "dynamic",
    complexity: "advanced",
    family: "King's Indian Defence",
  },
  E75: {
    color: "black",
    style: "modern",
    character: "dynamic",
    complexity: "advanced",
    family: "King's Indian Defence",
  },
  E76: {
    color: "black",
    style: "modern",
    character: "dynamic",
    complexity: "advanced",
    family: "King's Indian Defence",
  },
  E77: {
    color: "black",
    style: "modern",
    character: "dynamic",
    complexity: "advanced",
    family: "King's Indian Defence",
  },
  E78: {
    color: "black",
    style: "modern",
    character: "aggressive",
    complexity: "advanced",
    family: "King's Indian Defence",
  },
  E79: {
    color: "black",
    style: "modern",
    character: "aggressive",
    complexity: "advanced",
    family: "King's Indian Defence",
  },
  E80: {
    color: "black",
    style: "modern",
    character: "aggressive",
    complexity: "advanced",
    family: "King's Indian Defence",
    ideas: [
      "Sämisch Variation (KID): 5.f3 — White wants a big centre and attacks.",
      "Sharp and double-edged: Black typically plays ...c5 or ...e5.",
    ],
  },
  E81: {
    color: "black",
    style: "modern",
    character: "aggressive",
    complexity: "advanced",
    family: "King's Indian Defence",
  },
  E82: {
    color: "black",
    style: "modern",
    character: "aggressive",
    complexity: "advanced",
    family: "King's Indian Defence",
  },
  E83: {
    color: "black",
    style: "modern",
    character: "aggressive",
    complexity: "advanced",
    family: "King's Indian Defence",
  },
  E84: {
    color: "black",
    style: "modern",
    character: "aggressive",
    complexity: "advanced",
    family: "King's Indian Defence",
  },
  E85: {
    color: "black",
    style: "modern",
    character: "aggressive",
    complexity: "advanced",
    family: "King's Indian Defence",
  },
  E86: {
    color: "black",
    style: "modern",
    character: "aggressive",
    complexity: "advanced",
    family: "King's Indian Defence",
  },
  E87: {
    color: "black",
    style: "modern",
    character: "aggressive",
    complexity: "advanced",
    family: "King's Indian Defence",
  },
  E88: {
    color: "black",
    style: "modern",
    character: "aggressive",
    complexity: "advanced",
    family: "King's Indian Defence",
  },
  E89: {
    color: "black",
    style: "modern",
    character: "aggressive",
    complexity: "advanced",
    family: "King's Indian Defence",
  },
  E90: {
    color: "black",
    style: "modern",
    character: "aggressive",
    complexity: "advanced",
    family: "King's Indian Defence",
  },
  E91: {
    color: "black",
    style: "modern",
    character: "aggressive",
    complexity: "advanced",
    family: "King's Indian Defence",
  },
  E92: {
    color: "black",
    style: "modern",
    character: "aggressive",
    complexity: "advanced",
    family: "King's Indian Defence",
    ideas: [
      "Classical KID: ...e5 fights for the centre immediately.",
      "The most popular KID line; extremely rich theory.",
    ],
  },
  E93: {
    color: "black",
    style: "modern",
    character: "aggressive",
    complexity: "advanced",
    family: "King's Indian Defence",
  },
  E94: {
    color: "black",
    style: "modern",
    character: "dynamic",
    complexity: "advanced",
    family: "King's Indian Defence",
  },
  E95: {
    color: "black",
    style: "modern",
    character: "dynamic",
    complexity: "advanced",
    family: "King's Indian Defence",
  },
  E96: {
    color: "black",
    style: "modern",
    character: "aggressive",
    complexity: "advanced",
    family: "King's Indian Defence",
  },
  E97: {
    color: "black",
    style: "modern",
    character: "aggressive",
    complexity: "advanced",
    family: "King's Indian Defence",
    ideas: [
      "Mar del Plata Attack: ...e5 + ...Ne8-d6-f5 attacking idea.",
      "One of the most aggressive systems for Black in the KID.",
      "Geller, Bronstein, and Tal all used this to devastating effect.",
    ],
  },
  E98: {
    color: "black",
    style: "modern",
    character: "aggressive",
    complexity: "advanced",
    family: "King's Indian Defence",
  },
  E99: {
    color: "black",
    style: "modern",
    character: "aggressive",
    complexity: "advanced",
    family: "King's Indian Defence",
  },
};

// Generic fallbacks by ECO letter
const letterDefaults: Record<string, Omit<OpeningTag, "family">> = {
  A: {
    color: "white",
    style: "modern",
    character: "positional",
    complexity: "intermediate",
  },
  B: {
    color: "black",
    style: "modern",
    character: "dynamic",
    complexity: "intermediate",
  },
  C: {
    color: "white",
    style: "classical",
    character: "solid",
    complexity: "intermediate",
  },
  D: {
    color: "white",
    style: "classical",
    character: "positional",
    complexity: "intermediate",
  },
  E: {
    color: "black",
    style: "modern",
    character: "dynamic",
    complexity: "advanced",
  },
};

export function getTagsForEco(eco: string): OpeningTag {
  // Try exact 3-char match
  if (ecoTags[eco]) return ecoTags[eco];

  // Try same prefix + 0 (e.g. A23 → A20)
  const prefix2 = eco.slice(0, 1) + eco[1] + "0";
  if (ecoTags[prefix2]) return { ...ecoTags[prefix2], ideas: [] };

  // Fallback to letter default with generic family
  const letter = eco[0].toUpperCase();
  const def = letterDefaults[letter] ?? {
    color: "white",
    style: "classical",
    character: "solid",
    complexity: "beginner",
  };
  return {
    ...def,
    family: "Other",
    ideas: [],
  };
}
